---
- name: Install Ruby && Bundler
  hosts: all
  become: true
  tasks:
  # Установим в цикле все зависимости
  - name: Update all packages to the latest version
    apt:
      update_cache: yes

  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - git
      - ruby-full
      - ruby-bundler
      - build-essential
      